#adding checks for workflows
---
name: Checks

on: [push] #trigger to envoke for change made

jobs:
  test-linit:
    name: Test and Lint
    runs-on : ubuntu-20.04 #runner where we are running jobs on
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 #uses premade action given by github actions to perform login operations
        with:
          username: ${{ secrets.DOCKERHUB_USER }} #username
          password: ${{ secrets.DOCKERHUB_TOKEN }} #password
      - name: Checkout #premade action given by github does checkout latest code inside github action jobs
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test" #run unit-test for project
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8" #run lint using docker compose